[package]
name = "cashlog"
version = "0.1.0"
authors = ["Maciej Pietrzak"]

[dependencies]
iron = "*"
params = "*"
router = "*"
tera = "*"
time = "*"

[dependencies.postgres]
version = "*"
features = ["time"]
